name = "mojizukan-web"
main = "src/index.ts"
compatibility_date = "2026-06-27"
compatibility_flags = ["nodejs_als"]

[vars]
SENTRY_DSN = ""

[assets]
directory = "public"

[[d1_databases]]
binding = "DB"
database_name = "mojizukan-db"
database_id = "14e6c603-1287-4301-aa78-40e1b527985c"

[ai]
binding = "AI"

# GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, OPENAI_API_KEY は wrangler secret put で設定

# [[r2_buckets]]
# binding = "IMAGES"
# bucket_name = "mojizukan-images"
