name = "mojizukan-web"
main = "src/index.ts"
compatibility_date = "2026-06-27"

[assets]
directory = "public"

[[d1_databases]]
binding = "DB"
database_name = "mojizukan-db"
database_id = "14e6c603-1287-4301-aa78-40e1b527985c"

# [vars]
# OPENAI_API_KEY = "" # wrangler secret で設定する

# [[r2_buckets]]
# binding = "IMAGES"
# bucket_name = "mojizukan-images"
